//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://jomich.com/example/webservice", ConfigurationName="ServiceReference1.MyWebServiceSoap")]
    public interface MyWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://jomich.com/example/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/HelloWorld", ReplyAction="*")]
        WebServiceClient.ServiceReference1.HelloWorldResponse HelloWorld(WebServiceClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebServiceClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/sumar", ReplyAction="*")]
        double sumar(double value1, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<double> sumarAsync(double value1, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/restar", ReplyAction="*")]
        double restar(double value1, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/restar", ReplyAction="*")]
        System.Threading.Tasks.Task<double> restarAsync(double value1, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/mul", ReplyAction="*")]
        double mul(double value1, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/mul", ReplyAction="*")]
        System.Threading.Tasks.Task<double> mulAsync(double value1, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/div", ReplyAction="*")]
        double div(double value1, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/div", ReplyAction="*")]
        System.Threading.Tasks.Task<double> divAsync(double value1, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/potencia", ReplyAction="*")]
        double potencia(double value1, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/potencia", ReplyAction="*")]
        System.Threading.Tasks.Task<double> potenciaAsync(double value1, double value2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/raiz", ReplyAction="*")]
        double raiz(double value1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://jomich.com/example/webservice/raiz", ReplyAction="*")]
        System.Threading.Tasks.Task<double> raizAsync(double value1);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://jomich.com/example/webservice", Order=0)]
        public WebServiceClient.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceClient.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://jomich.com/example/webservice", Order=0)]
        public WebServiceClient.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceClient.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://jomich.com/example/webservice")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebServiceSoapChannel : WebServiceClient.ServiceReference1.MyWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebServiceSoapClient : System.ServiceModel.ClientBase<WebServiceClient.ServiceReference1.MyWebServiceSoap>, WebServiceClient.ServiceReference1.MyWebServiceSoap {
        
        public MyWebServiceSoapClient() {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClient.ServiceReference1.HelloWorldResponse WebServiceClient.ServiceReference1.MyWebServiceSoap.HelloWorld(WebServiceClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServiceClient.ServiceReference1.HelloWorldRequest inValue = new WebServiceClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceClient.ServiceReference1.HelloWorldRequestBody();
            WebServiceClient.ServiceReference1.HelloWorldResponse retVal = ((WebServiceClient.ServiceReference1.MyWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClient.ServiceReference1.HelloWorldResponse> WebServiceClient.ServiceReference1.MyWebServiceSoap.HelloWorldAsync(WebServiceClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            WebServiceClient.ServiceReference1.HelloWorldRequest inValue = new WebServiceClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceClient.ServiceReference1.HelloWorldRequestBody();
            return ((WebServiceClient.ServiceReference1.MyWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public double sumar(double value1, double value2) {
            return base.Channel.sumar(value1, value2);
        }
        
        public System.Threading.Tasks.Task<double> sumarAsync(double value1, double value2) {
            return base.Channel.sumarAsync(value1, value2);
        }
        
        public double restar(double value1, double value2) {
            return base.Channel.restar(value1, value2);
        }
        
        public System.Threading.Tasks.Task<double> restarAsync(double value1, double value2) {
            return base.Channel.restarAsync(value1, value2);
        }
        
        public double mul(double value1, double value2) {
            return base.Channel.mul(value1, value2);
        }
        
        public System.Threading.Tasks.Task<double> mulAsync(double value1, double value2) {
            return base.Channel.mulAsync(value1, value2);
        }
        
        public double div(double value1, double value2) {
            return base.Channel.div(value1, value2);
        }
        
        public System.Threading.Tasks.Task<double> divAsync(double value1, double value2) {
            return base.Channel.divAsync(value1, value2);
        }
        
        public double potencia(double value1, double value2) {
            return base.Channel.potencia(value1, value2);
        }
        
        public System.Threading.Tasks.Task<double> potenciaAsync(double value1, double value2) {
            return base.Channel.potenciaAsync(value1, value2);
        }
        
        public double raiz(double value1) {
            return base.Channel.raiz(value1);
        }
        
        public System.Threading.Tasks.Task<double> raizAsync(double value1) {
            return base.Channel.raizAsync(value1);
        }
    }
}
